### ISSUE TITLE
Problem with ILIAS 5.3 upgrade

### ISSUE THREAD

**Issue by davideOCGROUP** [studer-raimann/CtrlMainMenu#25]
Hi,
I'm trying to upgrade your plugin in a 5.3 installation but I obtain the following error:

"Cannot declare class ilUIHookPluginGUI, because the name is already in use"

Any idea about this bug?

Thanks you
Davide

**Comment by raimann** [comment]
Hello Davide,
As you wrote in the Ticket, the problem in the ILIAS-Installation. So I close this issue here.
